# Config for MineRP
default_job: "citizen" # The default job assigned when a player joins the server.
salary_frequency: 20 # How often in minutes are job salaries paid.

# Enable or Disable MySQL support and your database settings
MySQL:
  enabled: true
  host: localhost
  port: 3306
  database: mine_rp
  username: root
  password: ""