# Config for MineRP
default_job: "citizen"
salary_frequency: 20

# Enable or Disable MySQL support and your database settings
MySQL:
  enabled: true
  host: localhost
  port: 3306
  database: mine_rp
  username: root
  password: ""